name: yourspace-segmentation
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - pip:
      - -r Segmentation/requirements.txt
